#! /bin/bash

blogRoot="/Volumes/Internal/davidblack/GitHub/Blog/davidblackuk.github.io"

timestamp=$(exec date "+%Y-%m-%d")
title=""
for i in $*; do 
   title="$title-$i"; 
done;

name="$timestamp$title.md"
 
echo $name

file="$blogRoot/_posts/$name"

touch $file

echo "---" >> $file;
echo "layout: post" >> $file
echo "title: ${title//-/ }">>$file 
echo "tags: [ ]" >> $file 
echo "location: London, England" >>$file
echo "excerpt:" >> $file
echo "---" >> $file;
